name: pizza_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  very_good_analysis: ^8.0.0
  connectivity_plus: ^6.1.4
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^3.15.2
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  build_web_compilers: ^3.2.0
  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/core/logo.png"
  adaptive_icon_background: "#FF0000" # Replace with your desired color
  adaptive_icon_foreground: "assets/images/core/logo.png" # Replace with your desired image path
  # Add your other dependencies here.
  # For example:
  # http: ^0.13.3
  # provider: ^6.0.0
  # shared_preferences: ^2.0.6
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - assets/images/core/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
  # To add custom fonts to your application, add a section like this:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #         weight: normal
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #
  # For details regarding fonts from package dependencies, see
  # https://flutter.dev/custom-fonts/#from-packages